builds:
  -
    binary: wizard
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.version={{.Env.VERSION}}"
# Archive customization
archives:
  -
    format: tar.gz
    files:
      - LICENSE
      - README.md
